
import './globals.css'
import Providers from './provider'
import Body from './body'
import { cookies } from 'next/headers'

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  return (
    <html lang="en">
    <head />
    <Providers>
      <Body>{children}</Body>
    </Providers>
  </html>
  );
}
